### ISSUE TITLE
doesn't work with deps

### ISSUE THREAD

**Issue by acthp** [mgrandrath/jstestdriver-requirejs#1]
This appears to only work for modules without dependencies. If you create a second 'foo.js' module next to greeting.js and add ['foo'] to the define() call in greeting.js, the tests will not run.

I suspect this has something to do with the async call to fetch the dependency. If I add 'foo' to the require() call in greetingTest.js, the test will again run. However this is a very poor work-around, since it requires hard-coding all the dependencies into the test case.

**Comment by mgrandrath** [comment]
It does work for me. Can you provide more information about you setup or steps to reproduce?

**Comment by acthp** [comment]
I'm using jstd 1.3.4b, testing against chrome on osx and linux. I always
run with --reset to avoid problems with stale state. As I said in the
issue, I didn't do anything more than create a second module and add it as
a dependency to the first module.

I don't believe it can work with dependencies w/o other support, because
jstd does not get a callback when the dependencies are finished loading. So
it runs the test suite before the TestCase() calls are made, and returns
success running zero test cases.

Without an explicit sync mechanism, the best you can hope for is a race
condition that you sometimes win.

I was able to get them to sync by delegating script loading to requirejs,
in a loadSource plugin. Gist here:

https://gist.github.com/3557646

b.c.

On Mon, Aug 27, 2012 at 12:28 AM, Martin Grandrath <notifications@github.com

**Comment by mgrandrath** [comment]
Your gist suggests that you don't use my jsTestDriver.conf file and that you wrap your tests in `define()` instead of `require()` calls.

The important part in the configuration file is the directive

```
serve:
  - src/*.js
```

which lets jstd serve the files in the src/ directory.

> I don't believe it can work with dependencies w/o other support, because jstd does not get a callback when the dependencies are finished loading.

I don't see why jstd needs to get a callback. RequireJS handles the dependencies and executes the function passed to `require()` when all dependencies are ready.

Did you clone this project and follow the steps in the `README` file?

**Comment by acthp** [comment]
Yep, I went through the README and set up the serve config. If I hadn't
then my plugin wouldn't work. It's also using jstd to serve the files to
requirejs.

jstd needs a callback because otherwise it runs the suite before the
TestCase calls are made (or may, depending on which files load first). E.g.
if you have model1 which depends on module2, and a TestCase in test1, you
may get a sequence like so:

1) jstd does a GET of test1.js
2) test1.js finishes loading
3) test1 executes, calling require()
4) requirejs does a GET of module1, setting an onload callback, and returns
5) jstd (which now has the cpu since require() has returned) runs the test
suite. There are no test cases, since TestCase has not run. Result: success
running 0 test cases.
6) onload fires for module1. It does a define() with deps module2.
7) requirejs does a GET of module2
8) onload fires for module2. It does a define() with no deps, so the
define() callback is executed, defining module2.
9) all deps completed, the define() callback for module1 is executed,
defining module1
10) all deps completed, the require() callback in test1 is executed, making
the TestCase() calls. At this point it doesn't matter what requirejs does,
because the test run has already failed.

You'll get different results depending on browser cache, or file size,
etc. You can try to preload them using deps: ['module1'], but you'll end up
with the same result. requirejs will do a GET for module1.js and return.
Then jstd will do a GET for test1.js. Which one finishes first determines
whether the require() call in test1.js executes before jstd runs the suite.

b.c.

**Comment by mgrandrath** [comment]
Thank you very much for this detailed explanation! I can reproduce the problem and I included the AMDLoaderPlugin from your gist.

However, with the plugin loaded no tests are run in Opera. It seems that the `loadSource()` function never gets called. Can you reproduce this behavior and/or have an idea what the problem might be?

**Comment by acthp** [comment]
I haven't previously tried opera with jstd. I just tried it, and can't get
it to run any tests at all (with or without the loader plugin). It throws a
script error in jquery-min: cannot convert j to object. No idea what that's
about.

b.c.

**Comment by mgrandrath** [comment]
I consider this issue as closed then. Thank you again for your input!
